spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rsubd
    username: postgres
    password: 171198nik
  jpa:
    database: postgresql
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
server:
  port: 8080
  servlet:
    context-path: /api
